apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: inspircd-db
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: dbroot
        - name: MYSQL_DATABASE
          value: inspircd-db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: inspircd-db-secret
              key: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspircd-db-secret
              key: inspircd-db-password
        volumeMounts:
        - name: inspircd-db-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
  volumeClaimTemplates:
  - metadata:
      name: inspircd-db-data
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 5Gi

 
