apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
  labels:
    app: debian-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-container
  template:
    metadata:
      labels:
        app: debian-container
    spec:
      containers:
      - name: debian-container
        image: debian:latest
        ports:
        - containerPort: 22
        env:
        - name: TEST
          value: "Hello World!"
---
apiVersion: v1
kind: Service
metadata:
  name: debianservice
spec:
  selector:
    app: debian-container
  ports:
  - protocol: TCP
    port: 2222
    targetPort: 22

