apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQxMjM=   # Base64 encoded "password123"
  user-password: ZGVtbzEyMw==       # Base64 encoded "demo123"

